spring.application.name=chat
server.port=8085

spring.datasource.url=jdbc:mysql://project-db-campus.smhrd.com:3307/campus_24KDT_LI8_p2_4?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=campus_24KDT_LI8_p2_4
spring.datasource.password=smhrd4
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true